apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threatmind
resources:
  - ../../base
images:
  - name: threatmind/backend
    newTag: latest
  - name: threatmind/frontend
    newTag: latest
replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1
