apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threatmind
resources:
  - ../../base
images:
  - name: threatmind/backend
    newTag: stable
  - name: threatmind/frontend
    newTag: stable
